### ISSUE TITLE
Subscriptions not supported

### ISSUE THREAD

**Issue by MostafaGhafar** [Speedygeek/ZendeskApi_v2#354]
Hi,

Just I want to get all subscriptions of a given topic https://developer.zendesk.com/rest_api/docs/help_center/subscriptions#list-topic-subscriptions but I can't find a way to do that. It should be available and looks like zendeskApi.HelpCenter.Subscriptions.GetSubscriptionsByTopicId

Regards,
Mostafa

**Comment by mozts2005** [comment]
Based on my read of the core we need to add support for subscriptions entirely.
