### ISSUE TITLE
NuGet Package Update

### ISSUE THREAD

**Issue by DanielLatimerUns** [Speedygeek/ZendeskApi_v2#412]
I had a pull request merged in a week or so ago but I need a new version of the Nuget Package now that has the change I made in it. Would it be possible to get a new version published at some point please?

**Comment by mozts2005** [comment]
Yes a release to nuget.org will be made once the [3.10.0](
https://github.com/Speedygeek/ZendeskApi_v2/milestone/12) milestone has been completed. 

In the mean time you can use the myget feed  for accessing pre-release versions of the packge 

https://www.myget.org/feed/zendeskapi_v2_prerelease/package/nuget/ZendeskApi_v2

**Comment by DanielLatimerUns** [comment]
Thank you for letting me know.
