### ISSUE TITLE
Need help on GetTicketsByOrganizationIDAsync

### ISSUE THREAD

**Issue by ytwytw** [Speedygeek/ZendeskApi_v2#422]
Hi There,

I am working on getting tickets with pages and i have some issues 

```c#
var tickets1 = await api.Tickets.GetTicketsByOrganizationIDAsync(orgId, null, 1, TicketSideLoadOptionsEnum.Users);
```

i got my first 100 tickets

but if i do 

```c#
var tickets2 = await api.Tickets.GetTicketsByOrganizationIDAsync(orgId, null, 2, TicketSideLoadOptionsEnum.Users);
```
I am getting the same 100 tickets (tickets1 and tickets2 are the same)

Is that the right way to scroll differents of the tickets? I just trying to get all tickets from a Zendesk Organization.

Thanks,

**Comment by mattnis** [comment]
Did you try specifying 100 instead of null for the perPage parameter?
