### ISSUE TITLE
[REQUEST] Create a ticket as suspended

### ISSUE THREAD

**Issue by hingston** [Speedygeek/ZendeskApi_v2#430]
Was any progress made with Zendesk in regard to this?

https://github.com/Speedygeek/ZendeskApi_v2/blob/master/test/ZendeskApi_v2.Test/TicketTests.cs

```
        //[Test]
        //[Ignore("Need to Create Suspended Ticket Working with Zendesk support Team")]
        //public void CanGetSuspendedTickets()
        //{
        //    ZendeskApi_v2.Models.Tickets.Suspended.GroupSuspendedTicketResponse all = api.Tickets.GetSuspendedTickets();
        //    Assert.Greater(all.Count, 0);

        //    ZendeskApi_v2.Models.Tickets.Suspended.IndividualSuspendedTicketResponse ind = api.Tickets.GetSuspendedTicketById(all.SuspendedTickets[0].Id);
        //    Assert.AreEqual(ind.SuspendedTicket.Id, all.SuspendedTickets[0].Id);

        //    //There is no way to suspend a ticket so I can run a tests for recovering and deleting them
        //}
```

**Comment by mozts2005** [comment]
Yes this has been fixed and the unit test has been added back in.

**Comment by mozts2005** [comment]
if you want to make suspended tickets. please read this https://support.zendesk.com/hc/en-us/articles/203663246-Understanding-and-managing-suspended-tickets-and-spam

My understanding is that using the current APIs that is not an option.

**Comment by mozts2005** [comment]
If you have more questions just comment  and I will reopen the issue.
