### ISSUE TITLE
Getting Error 422 when it was working before

### ISSUE THREAD

**Issue by rgnos** [Speedygeek/ZendeskApi_v2#433]
Here's the response:
{Connection: keep-alive
X-Zendesk-API-Version: v2
X-Zendesk-Application-Version: v2308.25
X-Zendesk-API-Warn: Removed restricted keys ["ticket.id"] from parameters according to whitelist
X-Frame-Options: SAMEORIGIN
X-Rate-Limit: 700
X-Rate-Limit-Remaining: 699
Strict-Transport-Security: max-age=31536000;
X-Zendesk-Origin-Server: app27.pod13.usw2.zdsys.com
X-Request-Id: 4e94457668f1799b-SEA
X-Runtime: 0.272679
X-Zendesk-Request-Id: 617d2e58f7c8ce71fb42
Content-Length: 145
Cache-Control: no-cache
Content-Type: application/json; charset=UTF-8
Date: Wed, 19 Jun 2019 08:53:14 GMT
Set-Cookie: __cfduid=dbdfbd04068de724614a95e47ea3c82031560934393; expires=Thu, 18-Jun-20 08:53:13 GMT; path=/; domain=.volaris1506118788.zendesk.com; HttpOnly,__cfruid=5705680cb9e7c750b35f247d2c73656fc935f1ee-1560934394; path=/; domain=.volaris1506118788.zendesk.com; HttpOnly
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 4e94457668f1799b-SEA

}

**Comment by mozts2005** [comment]
Can you please provide an example of the code that is not working?

**Comment by rgnos** [comment]
Hi @mozts2005 , 

It is getting that error at the bolded part of the code
`var zendeskTicketID = SessionService.Get<int>(BCSKey.SessionKey.ZendeskTicketID);
            var ticket = buildJsonUpdate();
            var ticketJson = JsonConvert.SerializeObject(ticket).ToLower();
            byte[] byteArray = Encoding.UTF8.GetBytes(ticketJson);

            var username = WebConfigUtility.GetAppSetting("ZendeskUsername");
            var token = WebConfigUtility.GetAppSetting("ZendeskToken");
            var authorizationToken = Convert.ToBase64String(Encoding.GetEncoding("ISO-8859-1").GetBytes(username + "/token:" + token));
            var loginUrl =  WebConfigUtility.GetAppSetting("ZendeskUpdateURL").Replace("{ticket}", zendeskTicketID.ToString());

            WebRequest webRequestSaveClient = WebRequest.Create(loginUrl);
            ((HttpWebRequest)webRequestSaveClient).ContentType = "application/json";
            webRequestSaveClient.Method = "PUT";
            webRequestSaveClient.Headers.Add("Authorization", "Basic " + authorizationToken);
            ((HttpWebRequest)webRequestSaveClient).ContentLength = byteArray.Length;

            try
            {
                using (var stream = webRequestSaveClient.GetRequestStream())
                {
                    stream.Write(byteArray, 0, byteArray.Length);
                    stream.Close();
                }

                **WebResponse webResponseSaveClient = (HttpWebResponse)webRequestSaveClient.GetResponse();**

                using (var streamReader = new StreamReader(webResponseSaveClient.GetResponseStream()))
                {
                    var response = streamReader.ReadToEnd();
                    var zendeskTicketResponse = JsonConvert.DeserializeObject<ZendeskTicketResponse>(response);
                }
            }
            catch (Exception)
            {
                // ignored
            }`

this is the buildJsonUpdate method getting called
`private ZendeskTicketResponse buildJsonUpdate()
        {
            if (HasError)
            {
                ZendeskTicket.TicketResponse.Status = "open";
                ZendeskTicket.TicketResponse.Comment.Body = BCSKey.Constants.ZendeskCancellationFailedLabel;
                ZendeskTicket.TicketResponse.Comment.Public = false;
            }
            else
            {
                ZendeskTicket.TicketResponse.Status = "closed";
                ZendeskTicket.TicketResponse.Comment.Body = BCSKey.Constants.ZendeskCancellationSuccessLabel;
                ZendeskTicket.TicketResponse.Comment.Public = false;
            }

            return ZendeskTicket;
        }`

**Comment by mozts2005** [comment]
@rgnos thanks for the example. 

Are you only using the library models and not the full client?

**Comment by rgnos** [comment]
@mozts2005 

We are calling https://{ client }.zendesk.com/api/v2/ticket_forms/{id}.json

**Comment by mozts2005** [comment]
@rgnos Tickets and Ticket_Forms are two different APIs 


for a working example of working with Ticket_Forms please see this test case https://github.com/Speedygeek/ZendeskApi_v2/blob/458e85e3d3e9f097505d3d009596fc4b1b48de4a/test/ZendeskApi_v2.Test/TicketTests.cs#L935

for Tickets please see https://github.com/Speedygeek/ZendeskApi_v2/blob/458e85e3d3e9f097505d3d009596fc4b1b48de4a/test/ZendeskApi_v2.Test/TicketTests.cs#L558

**Comment by rgnos** [comment]
@mozts2005 
Correction, we are using Tickets, not Ticket Forms.
This issue is being encountered when Updating the ticket. Creating the ticket is working fine, but the WebResponse when updating is receiving Error 422. The status of the ticket is not closed.

**Comment by mozts2005** [comment]
@rgnos  

Here is can example of using the ZendeskApi_v2 library to preform an update to a ticket.  

https://github.com/Speedygeek/ZendeskApi_v2/blob/bb90668b63c8455d7396926d9321cf3e00b91430/test/ZendeskApi_v2.Test/TicketTests.cs#L406-L448


Note: I am not Zendesk staff. Here we support the ZendeskApi_v2 library and its use.

**Comment by rgnos** [comment]
Issue was intermittent but is fixed now.
