### ISSUE TITLE
newtonsoft

### ISSUE THREAD

**Issue by itsieber** [Speedygeek/ZendeskApi_v2#437]
PLS Update

**Comment by mozts2005** [comment]
More details on why? And to what version?

**Comment by itsieber** [comment]
The actual release would be nice.
When you use other apis in the same application that require a newer one, the zendeskapi_v2 dont like it and will crash with the error, missing the version 11.

You could also change to "allow higher versions".

I have no builded by own, for me it's run in the moment.

**Comment by mozts2005** [comment]
What version of ZendeskApi_v2 are you using?

**Comment by itsieber** [comment]
the newest

**Comment by mozts2005** [comment]
Based on my testing I am unable to replicate your issue. 

Before adding to Newtonsoft reference.

![image](https://user-images.githubusercontent.com/626061/60632036-30d41d80-9dc0-11e9-9fda-2bd6dfab73a0.png)

After adding direct reference

![image](https://user-images.githubusercontent.com/626061/60632061-68db6080-9dc0-11e9-8f5d-c8f6c4d46060.png)

Please create a sample that allows us to reproduce this issue.

**Comment by mozts2005** [comment]
I am closing as there has not been any feed back.
