### ISSUE TITLE
no verification email sent to end user

### ISSUE THREAD

**Issue by jimmyzhu710** [Speedygeek/ZendeskApi_v2#439]
Hi Team,

I created the api as following:
var api = new ZendeskApi(ZendeskUrl, UserEmail,ApiToken,locale);
Then created a normal ticket with requester email and name. But once the ticket was created, no verification email was sent to requester's email. Need your help. Thank you.

**Comment by jimmyzhu710** [comment]
Sorry the end user does receive a welcome email. But since I used the api token to create the ticket, the end user supposed to receive a ticket created notification email instead of a registration welcome email.

**Comment by mozts2005** [comment]
I think what you want is this https://develop.zendesk.com/hc/en-us/articles/360001068647-Making-API-requests-on-behalf-of-end-users-Zendesk-Support-

At this time we do not support this action I am working on it for the next version which is being worked on  as a rewrite from the ground up in a new repo.

**Comment by jimmyzhu710** [comment]
Hi Elizabeth,

Appreciate for your prompt reply. Wondering what is the time frame for your next version

**Comment by mozts2005** [comment]
Hope to have beta this time next year.

**Comment by jimmyzhu710** [comment]
Thank you Elizabeth:)

**Comment by mozts2005** [comment]
keep up to date here https://github.com/Speedygeek/ZendeskAPI
