### ISSUE TITLE
shared_phone_number not exposed in User Object

### ISSUE THREAD

**Issue by yonahs** [Speedygeek/ZendeskApi_v2#441]
I am trying to clean up my user list as I have doubles as some have the phone number as Direct  Line and some don't.

My problem is that the User object exposed in the API does not have the shared_phone_number property available.

Thanks

**Comment by mozts2005** [comment]
Shared_phone_number is a newer property. Will to take a PR to add it.

**Comment by cgray4263** [comment]
@mozts2005: If it is as simple as adding
```
        [JsonProperty("shared_phone_number")]
        public bool? SharedPhoneNumber { get; set; }
```
to the ZendeskApi_v2.Models.Users.User class (passes all unit tests but the suspended ticket one), should I commit that to my master so it can come along with the currently open pull request?

Note: It looks like the first user that has the number assigned to it will be reported as 'direct line' with shared_phone_number of false.  Subsequent users with that same number will report as true.  See the **Shared numbers** bullet in the "Understanding how phone numbers are linked to end-user profiles" section of [this Talk basics article](https://support.zendesk.com/hc/en-us/articles/230553307-Understanding-how-Talk-calls-become-tickets).

**Comment by mozts2005** [comment]
@cgray4263 yes please add it.

**Comment by yonahs** [comment]
Is this someone I can do myself or do I need to wait for you to release an update?

**Comment by mozts2005** [comment]
@yonahs  it will be part of the next release which should be this weekend.
