### ISSUE TITLE
GetCurrentQueueActivityAsync always returns 0

### ISSUE THREAD

**Issue by TimNilimaa** [Speedygeek/ZendeskApi_v2#445]
All data fields are 0 when calling GetCurrentQueueActivityAsync. This is due to the fact that what would be a CurrentQueueActivityResponse is returned from Zendesk, only a CurrentQueueActivity is used for deserialization.

**Comment by mozts2005** [comment]
closing as fix this will be release as part of 3.10.4

Which should be release next month. if you need access be for then for testing please use our myget feed  https://www.myget.org/feed/zendeskapi_v2_prerelease/package/nuget/ZendeskApi_v2
