### ISSUE TITLE
Api.Tickets.GetAudits(<ticketId>) fails on AutomaticAnswerSend Event (aka AnswerBot)

### ISSUE THREAD

**Issue by rwjdk** [Speedygeek/ZendeskApi_v2#449]
Hi 

If you have Zendesk answer bot (https://www.zendesk.com/answer-bot/) installed, In Audits of Type AutomaticAnswerSend the Body Of the Audit is not a simple string but an Array

**Example - Normal body**
![image](https://user-images.githubusercontent.com/7032102/61948993-b1de9900-afa9-11e9-9798-a31a61d37a0b.png)

**Example - Automatic Answer Send Body** 
![image](https://user-images.githubusercontent.com/7032102/61948923-7774fc00-afa9-11e9-9eda-9e603a591926.png)

**Because of this the Call to GetAudits(<ticket no>) fails as it can't turn the array into a string**
![image](https://user-images.githubusercontent.com/7032102/61948653-b8204580-afa8-11e9-9473-6162dd499c70.png)

I'm willing to help with fixing this issue but not sure how to do that right without break backward compatibility (I guess property could be turned into an object instead of a string would be the best approach)

**Comment by TimNilimaa** [comment]
I would argue that backward compatibility to a state that doesn’t work isn’t worth that much

**Comment by rwjdk** [comment]
Agree. It was more if there was a better fix + How many actually use Answer Bot (It been a pretty big disapointment so far IMHO)

**Comment by mozts2005** [comment]
I would agree with @TimNilimaa

If you have an Idea on now to fix this. We would welcome a Pull request.

**Comment by mozts2005** [comment]
One idea would be to leave the current property in place and add a new object body for when the property is not a string but I am not sure the work needed for this.

**Comment by rwjdk** [comment]
Not sure it would work. I will play around with what options there are and give back and update once I know what is possible and what is not

**Comment by mozts2005** [comment]
I have trust in you as you are using this code everyday. Submit what you think will work best.  And let us know why you picked it.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by rwjdk** [comment]
Pull Request sent. The solution ended up just changing the return type from string to object. The only other solution was to make a brand new model or everything and a new method and that would be a bit much for something that can be fixed with a simple .ToString() in places where people use it

**Comment by mozts2005** [comment]
fixed in #450 Please test using the myget feed. https://www.myget.org/feed/zendeskapi_v2_prerelease/package/nuget/ZendeskApi_v2

once I have confirmation that everything is working I will mark this issue closed sot that it can be part of the next release.

**Comment by rwjdk** [comment]
Just tested the 3.10.4.0 Alpha. Audit now works as expected :-)
