### ISSUE TITLE
Trying to Define Category when creating ticket

### ISSUE THREAD

**Issue by joshuatantonflynn** [Speedygeek/ZendeskApi_v2#454]
I'm using the ZendeskApi.Tickets.CreateTicket(ticket).Ticket; to create my ticket. Everything is working great so far.

However, I can't seam to find the Category property when defining my ticket. How would I set a specific Category for my Ticket?

I should note I have added the Category's tag with the Tags property. This does set the tag, but doesn't change the Category, once the Category is selected through zendesk UI the tag is then added twice, once from the original creation, and once when selecting the Category.

I expected it to be automatically set via the tag, because this is exactly how the location field works.

Thanks,

**Comment by mozts2005** [comment]
I am unable to find category in the docs. https://developer.zendesk.com/rest_api/docs/support/tickets

Is it possible that you have added it as a custom field?

**Comment by mozts2005** [comment]
please let me know what about this new test case is wrong. 
https://github.com/Speedygeek/ZendeskApi_v2/blob/master/test/ZendeskApi_v2.Test/TicketTestPart2.cs#L115-L138

**Comment by joshuatantonflynn** [comment]
Hi Mozts2005,

I don't see anything wrong with your test (assuming you are getting a success). But No matter how I edit my CustomFields, The resulting ticket always comes back with the same CustomField configuration. 20 fields. All with different ids, all null values (except for one, which is set automatically by one of my tags). It might be how our zendesk account is set up, but I don't have that level of access to see these settings. I even tried taking the resulting ticket after CreateTicket and editing the value of the CustomField I want changed, then calling UpdateTicketAsync. the resulting ticket still has this CustomField return null.

**Comment by mozts2005** [comment]
Please feel free to use our test account to continue your testing. Try cloning our repo and see if you get the same issues. 

But note every ticket will have a every custom field and if they are not set at any point in the tickets life they default to null. So having 20 nulls would be correct if your account has 20 custom field’s.

**Comment by joshuatantonflynn** [comment]
I will try to find some time to test with your test account.

I understand that all custom fields get defaulted to null. But what doesn't make sense is that this specific field is getting set to null while it has a value in the CustomField array I send in both CreateTicket and UpdateTicketAsync. I'll see if I can reproduce with your test account. But I doubt it will happen with that account. I think it's some setting with our account which I do not have access to. I will look into getting access for this.
