### ISSUE TITLE
Please add json property "audit_id" to comment model

### ISSUE THREAD

**Issue by tomkaczmarek** [Speedygeek/ZendeskApi_v2#457]

**Comment by abc516** [comment]
Hi @tomkaczmarek @mozts2005 I can tackle this issue if you need help.

**Comment by mozts2005** [comment]
You are more then welcome.

**Comment by abc516** [comment]
Cool. To clarify scope, all I have to do is add a new property to this model? https://github.com/Speedygeek/ZendeskApi_v2/blob/master/src/ZendeskApi_v2/Models/Tickets/Comment.cs

**Comment by mozts2005** [comment]
And unit test.

**Comment by tomkaczmarek** [comment]
Hi any progress on this?

**Comment by mozts2005** [comment]
@tomkaczmarek  I was about to add this property but I am unable to locate it i the docs 
can you provide a link or a way to replicate its population so that i can create a test case for it.

https://developer.zendesk.com/rest_api/docs/support/ticket_comments#json-format
