### ISSUE TITLE
Add create_or_update method to Users context

### ISSUE THREAD

**Issue by AlexanderKapelyukhovskiy** [Speedygeek/ZendeskApi_v2#460]
I noticed that there is _api.Users.CreateUser(user) but there is no _api.Users.CreateOrUpdateUser(user)
which should call following endpoint: https://developer.zendesk.com/rest_api/docs/support/users#create-or-update-user
It would be great to have this method in Users context.

**Comment by ThomasLuu00** [comment]
I would like to work on this.

**Comment by LauraLaureus** [comment]
I'm about to upload it.
