### ISSUE TITLE
search user by phone is not work

### ISSUE THREAD

**Issue by feiji127** [Speedygeek/ZendeskApi_v2#469]
when i want search end-user by phone number,but it not work ,i hava test with name and email ,it's all normal right,what problem about this?

here is my code:

` var searchTerms = string.Format("role:{0}", userType.GetEnumDescription());

            if (!string.IsNullOrEmpty(name))
                searchTerms += string.Format(" name:{0}", name);
            if (!string.IsNullOrEmpty(email))
                searchTerms += string.Format(" email:{0}", email);
            if (!string.IsNullOrEmpty(phoneNumber))
                searchTerms += string.Format(" phone:{0}", phoneNumber);

            var userResponse = await _api.Search.SearchForAsync<User>(searchTerms, "", "", 1, _pageSize);
            if (userResponse.Results.Count > 0)
                return userResponse.Results[0];
            else
                return null;`

i hava tested it with use name or email,but not work when i input then phoneNumber

**Comment by feiji127** [comment]
also ,i test it by search.json api,but it also not work,maybe it;s a bug of zendesk api but not issue about this project?

**Comment by mozts2005** [comment]
@feiji127  are you having issues with this ? 
https://github.com/Speedygeek/ZendeskApi_v2/blob/a42690860eb8a91a8db93e12560ff89e8962f2fe/test/ZendeskApi_v2.Test/UserTests.cs#L370-L376

If you have not tested this method please do.
