### ISSUE TITLE
Add property "removable" to TicketField 

### ISSUE THREAD

**Issue by russellshome** [Speedygeek/ZendeskApi_v2#474]
In my code I need to tell whether a field is a system field or a custom field.

Ref: https://developer.zendesk.com/rest_api/docs/support/ticket_fields
If false, this field is a system field that must be present on all tickets

This field seems to have been missed from
**https://github.com/Speedygeek/ZendeskApi_v2/blob/master/src/ZendeskApi_v2/Models/Tickets/TicketField.cs**

**Comment by mozts2005** [comment]
Looks like it is documented https://developer.zendesk.com/rest_api/docs/support/ticket_fields

Would gladly take a pull request to add it.

**Comment by russellshome** [comment]
I tested the results of the Zendesk API and it seems that this doesn't actually indicate whether a field is a system field or a custom field. The System fields Type and Priority have removable set to true.  

It seems that the only way I can  determine that a field is a custom field in the field list is to check that the type is not one of the 7 system field types.

**Comment by mozts2005** [comment]
please test with https://www.myget.org/feed/zendeskapi_v2_prerelease/package/nuget/ZendeskApi_v2/3.10.7-alpha1

**Comment by mozts2005** [comment]
Any update on testing?
