### ISSUE TITLE
Search requests by an end user

### ISSUE THREAD

**Issue by vmazzaroNybble** [Speedygeek/ZendeskApi_v2#487]
It seems it is not implemented search method in the requests API.
https://developer.zendesk.com/rest_api/docs/support/requests#search-requests

**Comment by mozts2005** [comment]
Can you use the search API? https://github.com/Speedygeek/ZendeskApi_v2/blob/master/src/ZendeskApi_v2/Requests/Search.cs#L138

**Comment by vmazzaroNybble** [comment]
I have tried, but unsuccessfully. 
I need to search requests with an end user role: 
`GET /api/v2/requests/search.json?query={search_string}`

**Comment by mozts2005** [comment]
can this be done using Postman? if so can you share the config?
