### ISSUE TITLE
Creating an anonymous ticket on behalf of end user

### ISSUE THREAD

**Issue by RobHudson72** [Speedygeek/ZendeskApi_v2#488]
According to ZenDesk documentation, the secret to creating a ticket on behalf of the end user is to omit the authorization header.  They refer to this as an "anonymous" ticket.  

I haven't been able to figure out how to do this in this API.  Just want to check if perhaps this is unsupported.

https://developer.zendesk.com/rest_api/docs/support/requests#create-request

**Comment by mozts2005** [comment]
@RobHudson72 

You still have to be authenticated to use the Zendesk API. 

if you have the feature enabled any authenticated user not just admins can override the requester. 
https://developer.zendesk.com/rest_api/docs/support/requests#creating-anonymous-requests

This is done in the API by setting the requester on the request object. 
https://github.com/Speedygeek/ZendeskApi_v2/blob/master/src/ZendeskApi_v2/Models/Requests/Request.cs#L56
https://github.com/Speedygeek/ZendeskApi_v2/blob/master/test/ZendeskApi_v2.Test/RequestTests.cs#L162

Please let us know if this helps.

**Comment by RobHudson72** [comment]
I was able to get this working directly from JavaScript, without an authentication header.  I believe that is by design, to support creation of tickets in a truly anonymous environment

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mozts2005** [comment]
javascript is outside the scope of this project but thank you for your feedback.
