### ISSUE TITLE
Job status model is not match with zendesk API response

### ISSUE THREAD

**Issue by GeneFang** [Speedygeek/ZendeskApi_v2#501]
### **we found JobStatus model from zendeskApi.JobStatuses.GetJobStatusAsync method is not matched response from zendesk job API.** 

![image](https://user-images.githubusercontent.com/10953069/106112834-b2508500-6188-11eb-90dd-8816f40a1ef6.png)
![image](https://user-images.githubusercontent.com/10953069/106112891-c2686480-6188-11eb-851a-9929aaba3fde.png)

**Here is response from zendesk API by postman:**
![image](https://user-images.githubusercontent.com/10953069/106113312-4f132280-6189-11eb-8420-0cc90893e991.png)

**Comment by mozts2005** [comment]
the results object is not documented other than to say that the differ depending on the type of the job. 

adding the details and index and error properties sounds fine. Would accept a PR to with these changes.
