### ISSUE TITLE
Visual Studio 2019 - "Unable to resolve the .NET SDK version as specified in the global.json located at..."

### ISSUE THREAD

**Issue by benconnolly-python** [Speedygeek/ZendeskApi_v2#503]
I am interested in your Zendesk_API_V2. I'm looking to get some assistance in getting the ZendeskApi_v2.Example working.
I'm running into Build issues using Visual Studio 2019. Specifically, I'm getting an error indicating "Unable to resolve the .NET SDK version as specified in the global.json located at..." - I downloaded using the ZIP file

![2021-02-11_14-50-40](https://user-images.githubusercontent.com/69989404/107690859-ad0b3400-6c78-11eb-9a6c-048448fd08c1.jpg)

**Comment by mozts2005** [comment]
@benconnolly-python the global.json used in this project references the .NET SDK version you need to have installed. 

https://github.com/Speedygeek/ZendeskApi_v2/blob/c3998db6710b8ed90dc81eee0661d1b8eecb5b3b/src/global.json#L3

Please install the correct version: https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.0.103-windows-x64-installer and restart your system.
