### ISSUE TITLE
Do I have to be an Zendesk Admin for my Email to work?

### ISSUE THREAD

**Issue by benconnolly-python** [Speedygeek/ZendeskApi_v2#505]
I got the example running using your solution.
Now I'm getting an authentication error.
My Zendesk User - is just a Agent - do I need to be an ADMIN?
Or did I simply fat finger my credentials?

System.Net.WebException: 'The remote server returned an error: (401) Unauthorized.Error content: {"error":"Couldn't authenticate you"} 
 Resource String: search.json?query=type:User bconnolly@halfpenny.com&page=1&sort_order=desc  + 
Date: Thu, 11 Feb 2021 20:59:26 GMT
Connection: keep-alive
Set-Cookie: __cfduid=d3b29a2db30cd977082cc124575ba04c11613077166; expires=Sat, 13-Mar-21 20:59:26 GMT; path=/; domain=.halfpennysupport.zendesk.com; HttpOnly; SameSite=Lax, __cfruid=b89cc38382063c60b8f8f7020966c71433b7a072-1613077166; path=/; domain=.halfpennysupport.zendesk.com; HttpOnly; Secure; SameSite=None
WWW-Authenticate: Basic realm="Web Password"
Strict-Transport-Security: max-age=31536000;
Cache-Control: no-cache
X-Zendesk-Origin-Server: classic-app-server-6cb5775644-kbhj5
X-Request-ID: 6200fe63e9800cad-EWR, 6200fe63e9800cad-EWR
X-Runtime: 0.158255
X-Zendesk-Zorg: yes
CF-Cache-Status: DYNAMIC
cf-request-id: 08347d527000000cad10beb000000001
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Report-To: {"group":"cf-nel","endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=uNjPAw0L5EwGf40VWCsHBs8vjHnXDJV%2Fq56Y58jqQHu%2BWVbWRTPSwF1W5OGmMWV511r64Patw42JWi912BIh0yKH%2FtwCKxjL%2BovuumPCpU2VjlQuJ83Z%2Fauu%2FyZ3"}],"max_age":604800}
NEL: {"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 6200fe63e9800cad-EWR
Content-Type: application/json; charset=UTF-8
Content-Length: 37

'

**Comment by benconnolly-python** [comment]
Disregard - I fat fingered my creds -

**Comment by mozts2005** [comment]
I am going to delete this issue as it leaks your username and Zendesk URL.
