### ISSUE TITLE
Support for rich-text features

### ISSUE THREAD

**Issue by ilCosmico** [Speedygeek/ZendeskApi_v2#506]
Any chance to add the support for the new rich-text-editing features via API?

https://support.zendesk.com/hc/en-us/articles/360057334013-Help-Center-adds-Rich-Text-Editing-to-your-Submit-a-Request-forms

![image](https://user-images.githubusercontent.com/8678145/111596509-87200480-87cd-11eb-95fb-98ccb1e32e6f.png)

I mean a way to tag and format blocks of source code when submitting tickets, like 
<code>
private void MyMethod()
{
    ...
}
</code>
or some kind of markdown for **Bold** or _Italic_ texts.

**Comment by mozts2005** [comment]
This would be a question that they Zendesk support team/ forums would be able to help with.
