### ISSUE TITLE
Organization.CreateOrUpdate

### ISSUE THREAD

**Issue by MelGrubb** [Speedygeek/ZendeskApi_v2#514]
The ZenDesk API supports Organizations.CreateOrUpdate (https://developer.zendesk.com/rest_api/docs/support/organizations#create-or-update-organization), but it is not exposed on the API. Is there a specific reason for this, or has no-one needed it before? I'm using the Users.CreateOrUpdate for users already, and it should theoretically save me a round trip.

**Comment by mozts2005** [comment]
@MelGrubb Looks as of no-one has needed it.  We would be more than happy to except this as a community contribution to the project.

**Comment by mozts2005** [comment]
please test using prelease version. https://www.myget.org/feed/zendeskapi_v2_prerelease/package/nuget/ZendeskApi_v2

Will release once we are given testing feedback.

**Comment by MelGrubb** [comment]
I'll have to circle back on this after current tasks, so it might be a few days before I swing around to our ZD integration stuff again, but I'll pull the version from there on a branch and see what I can do with it.
