### ISSUE TITLE
missing end_of_stream attribute from ticket export

### ISSUE THREAD

**Issue by JeremyCrookshank** [Speedygeek/ZendeskApi_v2#519]
Noticed we missed the end_of_stream attribute from ticket export so you couldn't call it recursively to get all tickets without this flag.

Reference: https://develop.zendesk.com/hc/en-us/articles/1500000071922
![image](https://user-images.githubusercontent.com/46864828/118497325-e0001080-b71c-11eb-9175-2e2e411480bb.png)

We should probably also bring in the cursor exports as they're recommended over the time based ones(https://develop.zendesk.com/hc/en-us/articles/1500000071922#cursor-based-incremental-exports) can create an separate issue for this if needed

**Comment by JeremyCrookshank** [comment]
Done in #518

**Comment by mozts2005** [comment]
please test and report back if everything is working as intended. 

 https://www.myget.org/feed/zendeskapi_v2_prerelease/package/nuget/ZendeskApi_v2/3.10.13-alpha1

**Comment by JeremyCrookshank** [comment]
Tested working, bool got set correctly.
