### ISSUE TITLE
Add sortBy to getTicketsForUserId

### ISSUE THREAD

**Issue by LuciooF** [Speedygeek/ZendeskApi_v2#528]
Currently, if I want to get the latest tickets for a specified userID.

I use 
`GroupTicketResponse GetTicketsByUserID(long userId, int? perPage = null, int? page = null, TicketSideLoadOptionsEnum sideLoadOptions = TicketSideLoadOptionsEnum.None);`

However, if I want the last tickets, I need to call this function once, to see the ticketCount, 
Then knowing the ticket count I can call this again to bring the last (say 5) tickets.
This means each time I'm searching for tickets for a specified User, I'm making 2 different calls.
Which is unnecessary and slower, it would save resources by adding a sortBy field parameter.
(It is possible that I have missed this being implemented somewhere else, but I cant seem to find it)
Thank you!

**Comment by LuciooF** [comment]
For my own future reference: https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/#sorting

**Comment by mozts2005** [comment]
would love to see a PR and please follow the pattern given by https://github.com/Speedygeek/ZendeskApi_v2/blob/500716e2a6e3330c44c7af5430fb79d33f0650b8/src/ZendeskApi_v2/Core.cs#L250

**Comment by mozts2005** [comment]
fixed by #529
