### ISSUE TITLE
Missing GetIncrementalTicketExportNextPageAsync function

### ISSUE THREAD

**Issue by luke-barnett** [Speedygeek/ZendeskApi_v2#555]
Looks like either an Async version of GetIncrementalTicketExportNextPage is missing or there is an updated recommendation for how to process subsequent pages for a ticket export?

If we just need to add the Async function in, I'm happy to do that but if there should be an obsolete tag added to it and pointing users to the preferred method that would also be good to sort out.

**Comment by mozts2005** [comment]
Would be happy to except a pull request that has this feature.

**Comment by luke-barnett** [comment]
PR created :)
https://github.com/Speedygeek/ZendeskApi_v2/pull/556
