### ISSUE TITLE
Ticket Audit Events, Macro Missing

### ISSUE THREAD

**Issue by CanisHelix** [Speedygeek/ZendeskApi_v2#560]
I'm trying to retrieve the Macro used from Tickets Audits, via the Events. But these fields are missing, how can I retrieve them?

For reference, the fields are documented here: https://developer.zendesk.com/documentation/ticketing/reference-guides/ticket-audit-events-reference/#macro-reference-event and they should be in the JSON response.

**Comment by mozts2005** [comment]
Very likely that the event class is missing the fields that you need. And the project would be willing to accept a pull request to add them

**Comment by CanisHelix** [comment]
Not used local/private Nuget's, but I can give this a try too
