### ISSUE TITLE
Adding multiple-entries to custom field: problem

### ISSUE THREAD

**Issue by PierreVelluet** [Speedygeek/ZendeskApi_v2#567]
Hello,

first of all, thanks for this wrapper.

I have a hard time figuring out what is the value type needed for a custom field of type "multi-select". For a single select choice, passing a string is ok, but a list of string doesnt work for multi - select's one.

My last attempt:

```csharp
CustomField themesField = new CustomField();
themesField.Id = MyFieldId;

List<string> themes = new List<string>();
foreach (Theme theme in SelectedTheme)
{
    themes.Add(theme. Name);
}
themesField.Value = themes;
ticketZendesk.CustomFields.Add(themesField);
```

Ticket is well created, though, the field's value "Thèmes" is empty.

Thanks in advance, i stay alert.

Have a great day

**Comment by mozts2005** [comment]
Can you create a failing test case that can replicate this bug?

**Comment by mozts2005** [comment]
As no test case has been submitted, I am going to close this issue. @PierreVelluet if you are still having this issue reopen and submit a pull request with failing test case.
