### ISSUE TITLE
Want a new feature for deleting tickets permanently

### ISSUE THREAD

**Issue by Abhijeetsinghjat** [Speedygeek/ZendeskApi_v2#573]
I am not able to find a wrapper method for deleting tickets permanently. Is there any way I can build that functionality on top of zendesk wrapper method or I am missing something

**Comment by PalaniappanC** [comment]
Hi @mozts2005 can you assign this ticket to my name

**Comment by PalaniappanC** [comment]
Hi @mozts2005 I am finding difficulties to setup the project in my local as I am using a mac now. Next week I will be getting a Windows machine with which I can complete the work. But I have started the analysis and pesudo code for the api to be implemented

**Comment by PalaniappanC** [comment]
Hi @mozts2005 . Please review this pr https://github.com/Speedygeek/ZendeskApi_v2/pull/580
