### ISSUE TITLE
Publish Nuget packages #3.12.3 has failed publishing

### ISSUE THREAD

**Issue by PeggyZWY** [Speedygeek/ZendeskApi_v2#584]
As seen [here](https://dev.azure.com/speedygeek/Zendesk/_build/results?buildId=871&view=logs&j=0ccccc7a-9630-5914-467b-15a9c61f0287), the publish pipeline has failed. And I'm in an urgent to use the new feature to permanently delete users which was added last week. Could you have a look of the failed pipeline? Thank you!

**Comment by mozts2005** [comment]
sorry it took so long but I have fixed the issue.

**Comment by PeggyZWY** [comment]
@mozts2005 Thanks a lot ;)
